#!/bin/bash
# Starts an experiment
#
# Options:
# --reset    or -r  : will reset everything blockchain related
# --start    or -s  : will start the experiment
# --startz   or -sz : will start with no visualization
# --logs     or -l  : will display monitor.log for all robots
# --python   or -p  : will display python console for all robots
# Example: 
# . starter -r -s -l -p

source experimentconfig.sh

echo "+-----------------------------------------------------------+"
echo "MAINFOLDER IS $MAINFOLDER"

echo "+-----------------------------------------------------------+"
echo "Updating the ARGoS XML file"

envsubst < $ARGOSTEMPLATE > $ARGOSFILE

# echo "+-----------------------------------------------------------+"
# echo "Sending python scripts"
# cp -r $EXPERIMENTFOLDER/controllers/docker/* $DOCKERFOLDER/geth/python_scripts/

echo "+-----------------------------------------------------------+"
echo "Sending smart contracts"
cp $SCFILE $TOYCHFOLDER/scs/deploy.py

echo "+-----------------------------------------------------------+"
echo "Cleaning logs folder..."

eval $(echo "rm -rf logs/{$(($NUMROBOTS+1))..1000}")

if [ "$EXPLORER" = "True" ]; then
    echo "+-----------------------------------------------------------+"
    echo "Starting Toychain explorer at http://${EXPLORER_HOST}:${EXPLORER_PORT}"
    echo "+-----------------------------------------------------------+"

    python3 "$EXPLORER_PATH/server.py" --host "$EXPLORER_HOST" --port "$EXPLORER_PORT" &

    EXPLORER_PID=$!
    trap "kill $EXPLORER_PID 2>/dev/null" EXIT
fi

echo "+-----------------------------------------------------------+"
echo "Starting Experiment"

for opt in "$@"; do
    if [[ $opt == "--logs" || $opt == "-l" ]]; then
        ./tmux-all -l monitor.log
    fi

    if [[ $opt == "--python" || $opt == "-p" ]]; then
        ./tmux-all -s python
    fi

    if [[ $opt == "--monitor" || $opt == "-m" ]]; then
        python3 loop_functions/loop_glassnode.py &
    fi

done

for opt in "$@"; do
    if [[ $opt == "--start" || $opt == "-s" ]]; then
        argos3 -c $ARGOSFILE
    fi

    if [[ $opt == "--start-novis" || $opt == "-sz" ]]; then
        argos3 -z -c $ARGOSFILE
    fi
done

